export const CONFIG = {
    letters: [
        // "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        // "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
        "_",
        // "Ф"
        "а", "б", "в", "г", "д", "е", "ё", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я", "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф", "Х", "Ц", "Ч", "Ш", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я",
        // //],
        // // [
        //     // "Х"
        //     // "Х", "X"
        // "ﱡ", "ﱢ", "ﱣ", "ﱞ", "ﱟ", "ﱠ",
        //     // "I", "L", "l",
        // "ㅤ", "ᅟ", "ᅠ", "ﾠ"
        //     //, "Ο", "O", "О"
        // [
    ],
    extraLetters: [
        // "а", "б", "в", "г", "д", "е", "ё", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х", "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я",
        // "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф", "Х", "Ц", "Ч", "Ш", "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
        // "︀", "︁", "︂", "︃", "︄", "︅", "︆", "︇", "︈", "︉", "︊", "︋",
        // "︌", "︍", "︎", "️"
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
        "_", "$"
    ],
    function_properties: [
        "clip",
        "createConicGradient",
        "createImageData",
        "createLinearGradient",
        "createPattern",
        "createRadialGradient",
        "drawFocusIfNeeded",
        "drawImage",
        "fill",
        "fillText",
        "getContextAttributes",
        "getImageData",
        "getLineDash",
        "getTransform",
        "isContextLost",
        "isPointInPath",
        "isPointInStroke",
        "measureText",
        "putImageData",
        "reset",
        "roundRect",
        "save",
        "scale",
        "setLineDash",
        "setTransform",
        "stroke",
        "strokeText",
        "transform",
        "arc",
        "arcTo",
        "beginPath",
        "bezierCurveTo",
        "clearRect",
        "closePath",
        "ellipse",
        "fillRect",
        "lineTo",
        "moveTo",
        "quadraticCurveTo",
        "rect",
        "resetTransform",
        "restore",
        "rotate",
        "strokeRect",
        "translate"
    ],
    object_properties: [
        // "nickname",
        // "info", "action",
        "angle",
        "update",
        "players",
        // "open",
        // "options", "market",
        // "grid",
        // "update",
        // "translate",
        // "button",
        // "marker",
        // "enabled",
        // "rotate",
        // "control", "attack", "unlock",
        // "active", "hit",
        "items",
        // /* World */
        "transition",
        // /* World */
        // /* User */
        // "fire",
        "well", "die",
        "timeout", "terminal", "ghost", "wait",
        // // /* User */
        // // /* Item */
        // // "draw",
        "draw_vehicle", "draw_life",
        "label",
        "winter", "desert",
        "tempest",
        // // /* Item */
        // // /* Interactors */
        "chest", "windmill", "furnace",
        "totem", "shop", "helmet", "weapon", "build",
        "padlock", "lockpick", "locked", "lock",
        // // /* Interactors */
        // // /* NetworkClient */
        // "message",
        "blocked",
        // "full",
        "gather",
        // "get_time",
        "freeze",
        "speed",
        "player", "right",
        // "claimed",
        "reconnect",
        "buttons",
        "units",
        // "connect"
        // // /* NetworkClient */
    ],
    array_properties: [
        "canvas",
        "globalAlpha", "globalCompositeOperation",
        "filter",
        "imageSmoothingEnabled", "imageSmoothingQuality",
        "strokeStyle", "fillStyle",
        "shadowOffsetX", "shadowOffsetY", "shadowBlur", "shadowColor",
        "lineWidth", "lineCap", "lineJoin", "lineDashOffset",
        "miterLimit",
        "font", "fontKerning", "fontStretch", "fontVariantCaps",
        "textAlign", "textBaseline",
        "direction", "letterSpacing",
        "textRendering",
        "wordSpacing",
        "Array",
        "Uint8Array", "Uint16Array", "Uint32Array",
        "JSON",
        // "time", "level", "name",
        // "x", "y",
        "id", "input",
        "createElement", "getContext",
        "prototype",
        "CanvasRenderingContext2D",
        "document",
        "getElementById",
        "addEventListener", "removeEventListener",
        "style",
        "requestAnimationFrame", "cancelAnimationFrame",
        // "textBaseline", "font",
        "push", "length",
        "left", "top", "display", "WebSocket",
        "innerHTML", "innerWidth", "innerHeight",
        "send",
        "close",
        // "status",
        // "readyState",
        // "value", "position", "view", "shift",
        // "onopen", "onmessage", "binaryType", "_current_id",
        // "data", "src", "pos", "nu",
        // "move", "item", "state", "selectedIndex",
        // "delay", "draw", "init",
        // "navigator", "userAgent", "indexOf",
        // "login", "password", "stringify", "IDLE",
        // "alert", "text", "list", "backgroundColor",
        // "replace", "parse", "now", "set", "activated",
        // "preventDefault", "select", "reset", "seed", "querySelector",
        // "loading", "toString",  "mapping", "get", "waiting", "alpha",
        "Date", "Error",
        "setTimeout", "clearTimeout",
        "XMLHttpRequest", "msgpack", "encode",
        "from",
        "onbeforeunload", "onload",
        // "getTime", "setTime",
        // "splice", "split", "sort", "charAt",
        // "charCode", "keyCode",
        // "add", "mode", "scale", "keys",   "target",
        "onerror", "fonts", "check",
        // "location", "href", "protocol", "cookie",
        // "match", "onUserLogin",
        // "volume", "hand", "loaded", "sample",
        // "modify", "forEach", "querySelectorAll", "toggle",
        "selectedIndex", "textContent", "classList", "type", "opacity",
        "exec", "toFixed", "fromCharCode",
        "Number", "String"
    ],
    strings: [
        "type", "string", "starve_mapping", "azerty", "qwerty",
        "starve_quality", "input_ratio", "high_ing", "low",
        "round", "middle", "px Baloo Paaji", "canvas", "2d",
        "destination-out", "source-over",
        "none", "inline-block", "click", "buy_", "change",
        "px", "azerty_ing", "qwerty_ing", "low_ing", "eject_member",
        "Starve.io", "_number", "_trad_number", "option_in_game",
        "agree_ing", "cancel_agree_ing", "quest_agree_ing",
        "auto_feed_agree_ing", "info_agree_ing", "pixelated_agree_ing",
        "mouseup", "mousedown", "mousemove", "keyup", "keydown",
        "DRAGON", "FOREST", "WINTER", "DESERT", "LAVA",
        "iblk",
        "</div>",
        "ws",
        "arraybuffer",
        "team_box", "contextmenu",
        "exploreForest", "exploreWinter", "exploreDesert", "exploreLava"
    ],
    reserved: [
        "nu", "i", "ssl", "DRAGON", "FOREST", "WINTER", "DESERT", "LAVA",
        "fod", "plm", "iblk", "cs", "de", "la", "fo", "re", "m", "login",
        "s", "p", "t", "f", "b", "r", "wtb", "g", "d", "a", "on",
        "server_region", "server_name", "method", "game_mode",
        "players", "max_players", "is_ssl", "keypress", "name",
        "bread", "score", "kill", "death", "time", "seasons",
        "bestScore", "bestKill", "bestTime", "scoreTotal",
        "firstName", "privateServer", "privateServerTime", "kit",
        "skins", "accessories", "books", "bags", "crates",
        "id", "recipe", "water", "well", "time", "login", "password",
        "workbench", "fire", "workbench", "Content-type",
        "rand", "type"
    ],
    js_confuser: {
        calculator: true,
        compact: true,
        dispatcher: 0.4,
        globalConcealing: 0.5,
        identifierGenerator: 'mangled',
        lock: {
            antiDebug: true,
            integrity: true,
            selfDefending: true,
        },
        objectExtraction: 0.5,
        opaquePredicates: 0.5,
        renameGlobals: true,
        renameVariables: true,
        shuffle: false,
        stringConcealing: 0.6,
        target: 'browser'
    },
    minify: {
        window: true,
        strings: true,
        arrays: true,
        object_properties: true,
        array_methods: true,
        math_methods: true,
        functions: true,
        terser: true
    }
};
